-- CreateEnum
CREATE TYPE "TransmissionType" AS ENUM ('MANUAL', 'AUTOMATIC');
CREATE TYPE "FuelType" AS ENUM ('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID', 'PLUGIN_HYBRID');
CREATE TYPE "PlateState" AS ENUM ('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT');

-- AlterEnum
ALTER TYPE "CarStatus" ADD VALUE IF NOT EXISTS 'BOOKED';
ALTER TYPE "CarStatus" ADD VALUE IF NOT EXISTS 'DISABLED';

-- AlterTable Car - Add new columns
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "categoryId" TEXT;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "variant" TEXT;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "plateState" "PlateState" DEFAULT 'NSW';
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "engineSize" TEXT;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "horsepower" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "transmissionType" "TransmissionType" DEFAULT 'AUTOMATIC';
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "fuelType" "FuelType" DEFAULT 'PETROL';
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "fuelTankCapacity" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "seats" INTEGER DEFAULT 5;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "doors" INTEGER DEFAULT 4;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "bagsCapacity" INTEGER DEFAULT 2;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "weeklyRateCents" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "monthlyRateCents" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "depositAmountCents" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "lateFeePerDayCents" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "nextServiceKm" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "lastServiceDate" TIMESTAMP(3);
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "lastServiceKm" INTEGER;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "reverseCamera" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "bluetooth" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "cruiseControl" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "sunroof" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "childSeatSupport" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "appleCarPlay" BOOLEAN DEFAULT false;
ALTER TABLE "Car" ADD COLUMN IF NOT EXISTS "androidAuto" BOOLEAN DEFAULT false;

-- Rename column if exists
ALTER TABLE "Car" RENAME COLUMN "make" TO "brand";

-- AlterTable CarCategory - Add new columns
ALTER TABLE "CarCategory" ADD COLUMN IF NOT EXISTS "icon" TEXT;
ALTER TABLE "CarCategory" ADD COLUMN IF NOT EXISTS "basePriceAdjustment" DOUBLE PRECISION;
ALTER TABLE "CarCategory" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Car_tenantId_categoryId_idx" ON "Car"("tenantId", "categoryId");
CREATE INDEX IF NOT EXISTS "Car_tenantId_brand_idx" ON "Car"("tenantId", "brand");
CREATE INDEX IF NOT EXISTS "Car_tenantId_transmissionType_idx" ON "Car"("tenantId", "transmissionType");
CREATE INDEX IF NOT EXISTS "Car_tenantId_fuelType_idx" ON "Car"("tenantId", "fuelType");

-- AddForeignKey
ALTER TABLE "Car" ADD CONSTRAINT "Car_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "CarCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
